sudo: required
services:
- docker
notifications:
  email: false
script:
- docker build -t gns3-gui-test .
- docker run gns3-gui-test
- sudo pip install twine
#before_deploy:
#    sudo pip install twine
deploy:
  provider: pypi
  user: noplay
  password:
    secure: FofcqlJjgqf2jaDaXpLHeigVoexbrOz3WwnDuiJpwJxeFUlPY8s2cQs/Bm+dzxzZaOaGiVE0A83v/Xa10yD5tflThHt4sqYJK3iQCinA7wgeAlDimB4xrWUNplfNJZ/Eod5Ssa++E02W+3i29PxpXY//mjCY7qDxaoxul1gnFJY=
  on:
    tags: true
    repo: GNS3/gns3-gui
