version: '{build}-{branch}'

image: Visual Studio 2017

platform: x64

on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))


environment:
    PYTHON: "C:\\Python36-x64"
    DISTUTILS_USE_SDK: "1"

install:
   - cinst nmap
   - "%PYTHON%\\python.exe -m pip install -r dev-requirements.txt"
   - "%PYTHON%\\python.exe -m pip install -r win-requirements.txt"

build: off

test_script:
   - "%PYTHON%\\python.exe -m pytest -v"
